/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package metavi.android.wv;

import java.util.HashMap;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiActivitySupport;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;
import android.content.Intent;


@Kroll.module(name="Natwebview", id="metavi.android.wv")
public class NatwebviewModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "NatwebviewModule";
	private static final boolean DBG = TiConfig.LOGD;
	String UrlVideo = null;

	public NatwebviewModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
	}

	@Kroll.method
	public void openWeb(HashMap args) {
		KrollDict options = new KrollDict(args);
		Log.i(LCAT, "OK!??");
		Activity activity = TiApplication.getAppCurrentActivity();
        TiActivitySupport support = (TiActivitySupport) activity;
		

		Intent i = new Intent(activity, WebViewCActivity.class); //new Intent();
		UrlVideo = (String) options.get("url");
		Log.i(LCAT, UrlVideo);
		i.putExtra("UrlVideo", UrlVideo);
		activity.startActivity(i);
//		 support.launchActivityForResult(i, requestCode, this); //Utility.activity_example
	}

}

